Vectorstores
averikitsch/langchaingo pull request #3
Opened 2024-12-27 20:09 UTC by Diegoplas

### PR Checklist
Implementation of vectorstores which uses postgresDB engine pool.

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x] Describes the source of new concepts.
- [x] References existing implementations as appropriate.
- [ ] Contains test coverage for new functions.
- [ ] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

2025-01-02 18:08 UTC, kurtisvg requested changes

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +func NewVectorStore(ctx context.Context, opts ...VectoreStoresOption) (vectorStore, error) {
Returning an unexported type will cause issues for users (most notably they won't be able to have a pointer to that type in other structs they build) 

Two alternatives are:
1. Exporting the type (but leaving fields private)
2. Creating a new interface and change the func to return that interface type instead

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +// NewVectorStore creates a new Store with options.
```suggestion
// NewVectorStore creates a new VectorStore with options.
```

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +	return filtered
nit: I think this function is only use in the one place. Could we inline it?

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +	opts := vectorstores.Options{}
This doesn't get set anywhere -- do we need a [s.getOptions](https://github.com/tmc/langchaingo/blob/238d1c713de3ca983e8f6066af6b9080c9b0e088/vectorstores/pgvector/pgvector.go#L233C12-L233C22) or something else to apply options to a config struct?

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +	sql := fmt.Sprintf(`INSERT INTO %s (uuid, document, embedding, cmetadata, collection_id)
One thing with this vs the Pgvector design is that we want to be able to support a flexible schema. Is that planning to be addressed in a later PR?

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +		vs.collectionName = opts.NameSpace
Is it safe to overwrite something attached to vs here?

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +LIMIT $3`, vs.embeddingTableName,
can this string get moved into a const to improve readability of this section?

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +	collectionTableName string
I'm confused as to why we would need all 3 of these fields.

@averikitsch fyi

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +        REINDEX INDEX <changeTableName>;`)
does this need to be on a newline?

Also, it this a TODO?

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +        CREATE INDEX IF NOT EXISTS <changeTableName> ON <changeTableName>;`)
I'm somewhat confused by the API of this function -- shouldn't it take in parameters for an index in order to work?

2025-01-02 18:08 UTC, kurtisvg commented on vectorstores/alloydb/vectorestores.go
> +func (vs *vectorStore) DropVectorIndex(ctx context.Context) error {
Please add doc strings to all of these functions

2025-01-09 00:53 UTC, averikitsch commented on vectorstores/alloydb/vectorestores.go
> +	collectionTableName string
This is following the PGVector implementation, not the python canonical. 

fyi @Diegoplas

2025-01-16 00:46 UTC, closed without merging